# The URL the site will be built for
base_url = "https://threat-defuser.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[extra]

navigation = [
  { name = "About", path = "/" },
  { name = "Work packages", path = "/work-packages/" },
  { name = "Kick-off", path = "/kick-off/" },
  { name = "Team", path = "/team/" },
  { name = "Open positions", path = "/positions/" },
# { name = "Blog", path = "/blog/" },
  { name = "GitHub", path = "https://github.com/threat-defuser" }
]

icon = "favicon.ico"
profile_small = "profile.png"

accent = "#05a081"
accent_light = "#82d0c0"

footer_about = """
Contact: [Laura Janda](http://ansatte.uit.no/laura.janda/).
This site is hosted on [GitHub](https://github.com/threat-defuser/threat-defuser.org).
[Here](https://github.com/threat-defuser/threat-defuser.org/blob/master/README.md) are instructions
on how to apply/suggest changes.
"""
